"""short url table

Revision ID: b5cc07dbdded
Revises: 
Create Date: 2021-06-01 20:57:10.873301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5cc07dbdded'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enterURL',
    sa.Column('urlId', sa.Integer(), nullable=False),
    sa.Column('longURL', sa.String(length=200), nullable=True),
    sa.Column('shortURL', sa.String(length=10), nullable=True),
    sa.Column('createdAt', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('urlId'),
    sa.UniqueConstraint('shortURL'),
    sa.UniqueConstraint('shortURL')
    )
    op.create_index(op.f('ix_enterURL_longURL'), 'enterURL', ['longURL'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_enterURL_longURL'), table_name='enterURL')
    op.drop_table('enterURL')
    # ### end Alembic commands ###
