"""reduced url input 

Revision ID: 41c2ee24addd
Revises: 
Create Date: 2019-03-18 23:42:23.066635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41c2ee24addd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enterURL',
    sa.Column('urlId', sa.Integer(), nullable=False),
    sa.Column('longURL', sa.String(length=64), nullable=True),
    sa.Column('shortURL', sa.String(length=10), nullable=True),
    sa.Column('createdAt', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('urlId'),
    sa.UniqueConstraint('shortURL')
    )
    op.create_index(op.f('ix_enterURL_longURL'), 'enterURL', ['longURL'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_enterURL_longURL'), table_name='enterURL')
    op.drop_table('enterURL')
    # ### end Alembic commands ###
